# Auto-label rules for pull requests
# Maps label names → file path globs that trigger the label

"tmcmc-core":
  - changed-files:
    - any-glob-to-any-file:
      - data_5species/core/**
      - data_5species/model_config/**

"fem":
  - changed-files:
    - any-glob-to-any-file:
      - FEM/**

"docs":
  - changed-files:
    - any-glob-to-any-file:
      - docs/**
      - wiki/**
      - "*.md"
      - CITATION.cff
      - CONTRIBUTING.md

"ci":
  - changed-files:
    - any-glob-to-any-file:
      - .github/**

"config":
  - changed-files:
    - any-glob-to-any-file:
      - data_5species/model_config/**
      - "*.json"

"sweep":
  - changed-files:
    - any-glob-to-any-file:
      - run_bridge_sweep.py
      - analyze_sweep_results.py
